sudo: required
services:
  - docker

before_install:
  - docker build -t exmonaka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true exmonaka/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-698252471125"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
